version: '3.7'
services:
  postgres-db:
    image: postgres:14.3
    restart: always
    container_name: metrics-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=organization_statistics-db
    ports:
      - "5432:5432"